# -*- coding: utf-8 -*-
"""Untitled4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_3HaEs1dFexm4Fo9srSTV5bFGVp2sjQb
"""

!pip install gtts

from gtts import gTTS
import os

def text_to_speech(text, lang='en'):
    tts = gTTS(text=text, lang=lang)
    tts.save("output.mp3")
    os.system("mpg321 output.mp3")  # This command may vary depending on your system

# Example usage
text = "Hello, this is a text-to-speech conversion example."
text_to_speech(text)

import requests

def fetch_currency_conversion(base_currency, target_currency, amount):
    api_key = 'YOUR_API_KEY'  # Replace with your actual API key
    url = f'https://v6.exchangerate-api.com/v6/{api_key}/latest/{base_currency}'

    try:
        response = requests.get(url)
        response.raise_for_status()  # Raise an error for bad status codes
        data = response.json()

        if 'conversion_rates' in data:
            conversion_rate = data['conversion_rates'][target_currency]
            converted_amount = amount * conversion_rate
            return converted_amount
        else:
            return "Error: 'conversion_rates' not found in the response."
    except requests.exceptions.RequestException as e:
        return f"Error fetching data from the API: {e}"
    except ValueError as e:
        return f"Error decoding JSON response: {e}"

# Example usage
base_currency = "USD"
target_currency = "EUR"
amount = 100

converted_amount = fetch_currency_conversion(base_currency, target_currency, amount)
print(amount, base_currency, 'is equal to' ,converted_amount ,target_currency)